id: app
title: Organization Intranet
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/organization-intranet
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of Organization Intranet
    long: Generates compliance documentation of Organization Intranet as it pertains
      to managing the security of CUI (Controlled Unclassified Information) as per
      NIST SP 800-171 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Organization Intranet are web pages available internally to the organization.

    This application will make sure you are properly using Organization Intranet to
    protect CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist800171r1_3_2_3
  title: NIST SP 800-171 3.2.3 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Organization Intranet to provide security awareness training
    on recognizing and reporting potential indicators of insider threat. Organization
    Intranet are web pages available internally to the organization.

- id: ssp_nist800171r1_3_9_2
  title: NIST SP 800-171 3.9.2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Organization Intranet to ensure that CUI and organizational
    systems containing CUI are protected during and after personnel actions such as
    terminations and transfers. Organization Intranet are web pages available internally
    to the organization.

