id: app
title: Nginx Web Server
type: project
version: 1
protocol: web_server
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.95
  source_url: https://github.com/GovReady/some-repo-here
  description:
    short: |
      Configure an Nginx web server so you can get an Interim Authority to Operate.
    long: |
      This app will help you configure and operate an Nginx web server so you can get an Interim Authority to Operate.
  recommended_for:
  - key_short: Org
    value: Large
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
questions:
- id: system_details
  title: System Details
  type: module
  module-id: system_details
output:
- ssp_template.md
